name: ROS 2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ros_ci:
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt update && apt install -y \
            python3-colcon-common-extensions \
            python3-rosdep \
            libnlohmann-json-dev
          rosdep update
          rosdep install --from-paths . --ignore-src -y

      - name: Build and Test
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --packages-select bob_audio
          colcon test --packages-select bob_audio --event-handlers console_direct+
          colcon test-result --all --verbose
